DELETE FROM Fatura
DELETE FROM Instituicao
DELETE FROM Administrador
DELETE FROM Artista
DELETE FROM GeneroMusical
DELETE FROM Instituicao
DELETE FROM Leilao
DELETE FROM Licitador
DELETE FROM Notificacao